package org.smap.sdal.managers;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.ResourceBundle;
import java.util.logging.Logger;

import org.smap.sdal.Utilities.ApplicationException;
import org.smap.sdal.Utilities.GeneralUtilityMethods;
import org.smap.sdal.model.QuestionForm;
import org.smap.sdal.model.ReferenceFilter;
import org.smap.sdal.model.SqlFrag;

/*****************************************************************************

This file is part of SMAP.

SMAP is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

SMAP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with SMAP.  If not, see <http://www.gnu.org/licenses/>.

 ******************************************************************************/

/*
 * Manage the reference_filter table.  A reference filter is a static pseudo-SQL filter,
 * defined on a linker survey bundle, that restricts the reference data pulled from a
 * source survey.  Defined at the group level (like roles) per (linker, source) pair.
 */
public class ReferenceFilterManager {

	private static Logger log = Logger.getLogger(ReferenceFilterManager.class.getName());

	ResourceBundle localisation = null;

	public ReferenceFilterManager(ResourceBundle l) {
		localisation = l;
	}

	/*
	 * Get all configured filters for a linker survey bundle
	 */
	public ArrayList<ReferenceFilter> getFilters(Connection sd, String linkerSIdent) throws Exception {

		ArrayList<ReferenceFilter> filters = new ArrayList<>();

		String sql = "select rf.id, rf.linker_s_ident, rf.linked_s_ident, rf.filter, rf.enabled, "
				+ "(select display_name from survey where ident = rf.linked_s_ident) as linked_name "
				+ "from reference_filter rf "
				+ "where rf.linker_s_ident = ? "
				+ "order by linked_name asc";
		PreparedStatement pstmt = null;
		try {
			pstmt = sd.prepareStatement(sql);
			pstmt.setString(1, linkerSIdent);
			ResultSet rs = pstmt.executeQuery();
			while (rs.next()) {
				ReferenceFilter rf = new ReferenceFilter();
				rf.id = rs.getInt("id");
				rf.linkerSIdent = rs.getString("linker_s_ident");
				rf.linkedSIdent = rs.getString("linked_s_ident");
				rf.filter = rs.getString("filter");
				rf.enabled = rs.getBoolean("enabled");
				rf.linkedSName = rs.getString("linked_name");
				filters.add(rf);
			}
		} finally {
			if (pstmt != null) try { pstmt.close(); } catch (Exception e) {}
		}
		return filters;
	}

	/*
	 * Get the single enabled filter for a (linker, source) pair, or null.
	 * Called during CSV generation.
	 */
	public ReferenceFilter getFilter(Connection sd, String linkerSIdent, String linkedSIdent) throws Exception {

		ReferenceFilter rf = null;

		String sql = "select id, linker_s_ident, linked_s_ident, filter, enabled "
				+ "from reference_filter "
				+ "where linker_s_ident = ? "
				+ "and linked_s_ident = ? "
				+ "and enabled";
		PreparedStatement pstmt = null;
		try {
			pstmt = sd.prepareStatement(sql);
			pstmt.setString(1, linkerSIdent);
			pstmt.setString(2, linkedSIdent);
			ResultSet rs = pstmt.executeQuery();
			if (rs.next()) {
				rf = new ReferenceFilter();
				rf.id = rs.getInt("id");
				rf.linkerSIdent = rs.getString("linker_s_ident");
				rf.linkedSIdent = rs.getString("linked_s_ident");
				rf.filter = rs.getString("filter");
				rf.enabled = rs.getBoolean("enabled");
			}
		} finally {
			if (pstmt != null) try { pstmt.close(); } catch (Exception e) {}
		}
		return rf;
	}

	/*
	 * Validate a filter's pseudo-SQL and persist it (upsert), then force any linked CSV
	 * files generated by the linker bundle to be regenerated.
	 */
	public void saveFilter(Connection sd, ReferenceFilter rf) throws Exception {

		validateFilter(sd, rf.linkedSIdent, rf.filter);

		String sqlUpdate = "update reference_filter set filter = ?, enabled = ? "
				+ "where linker_s_ident = ? and linked_s_ident = ?";
		String sqlInsert = "insert into reference_filter (id, linker_s_ident, linked_s_ident, filter, enabled) "
				+ "values (nextval('reference_filter_seq'), ?, ?, ?, ?)";
		PreparedStatement pstmtUpdate = null;
		PreparedStatement pstmtInsert = null;
		try {
			pstmtUpdate = sd.prepareStatement(sqlUpdate);
			pstmtUpdate.setString(1, rf.filter);
			pstmtUpdate.setBoolean(2, rf.enabled);
			pstmtUpdate.setString(3, rf.linkerSIdent);
			pstmtUpdate.setString(4, rf.linkedSIdent);
			int count = pstmtUpdate.executeUpdate();
			if (count == 0) {
				pstmtInsert = sd.prepareStatement(sqlInsert);
				pstmtInsert.setString(1, rf.linkerSIdent);
				pstmtInsert.setString(2, rf.linkedSIdent);
				pstmtInsert.setString(3, rf.filter);
				pstmtInsert.setBoolean(4, rf.enabled);
				pstmtInsert.executeUpdate();
			}
		} finally {
			if (pstmtUpdate != null) try { pstmtUpdate.close(); } catch (Exception e) {}
			if (pstmtInsert != null) try { pstmtInsert.close(); } catch (Exception e) {}
		}

		invalidateLinkerFiles(sd, rf.linkerSIdent);
	}

	/*
	 * Delete a filter and force regeneration of the linker's linked CSV files.
	 */
	public void deleteFilter(Connection sd, String linkerSIdent, String linkedSIdent) throws Exception {

		String sql = "delete from reference_filter where linker_s_ident = ? and linked_s_ident = ?";
		PreparedStatement pstmt = null;
		try {
			pstmt = sd.prepareStatement(sql);
			pstmt.setString(1, linkerSIdent);
			pstmt.setString(2, linkedSIdent);
			pstmt.executeUpdate();
		} finally {
			if (pstmt != null) try { pstmt.close(); } catch (Exception e) {}
		}

		invalidateLinkerFiles(sd, linkerSIdent);
	}

	/*
	 * Validate that the filter parses and only references questions in the source survey bundle.
	 * A blank filter is valid (no restriction).
	 */
	public void validateFilter(Connection sd, String linkedSIdent, String filter) throws Exception {

		if (filter == null || filter.trim().length() == 0) {
			return;
		}

		// Parse the pseudo-SQL - this extracts the ${...} question names into humanNames
		SqlFrag sq = new SqlFrag();
		sq.addSqlFragment(filter, false, localisation, 0);

		// SqlFrag only extracts names, it does not confirm they exist, so check them here
		SurveyManager sm = new SurveyManager(localisation, "UTC");
		HashMap<String, QuestionForm> refQuestionMap = sm.getGroupQuestionsMap(sd, linkedSIdent, null, false);

		for (String name : sq.humanNames) {
			if (refQuestionMap.get(name) == null) {
				// "not found in form" - the referenced question is not in the source survey
				throw new ApplicationException(name + " " + localisation.getString("imp_nfi"));
			}
		}
	}

	/*
	 * Get the source surveys that the linker bundle links to, so a filter can be configured
	 * against each.  Existing filters are merged in.
	 */
	public ArrayList<ReferenceFilter> getLinkableSources(Connection sd, String linkerSIdent) throws Exception {

		ArrayList<ReferenceFilter> sources = new ArrayList<>();

		String sql = "select distinct src.group_survey_ident as ident, "
				+ "(select display_name from survey where ident = src.group_survey_ident) as name "
				+ "from form_dependencies fd "
				+ "join survey linker on fd.linker_s_id = linker.s_id "
				+ "join survey src on fd.linked_s_id = src.s_id "
				+ "where linker.group_survey_ident = ? "
				+ "and not src.deleted "
				+ "order by name asc";
		PreparedStatement pstmt = null;
		try {
			pstmt = sd.prepareStatement(sql);
			pstmt.setString(1, linkerSIdent);
			ResultSet rs = pstmt.executeQuery();
			while (rs.next()) {
				ReferenceFilter rf = new ReferenceFilter();
				rf.linkerSIdent = linkerSIdent;
				rf.linkedSIdent = rs.getString("ident");
				rf.linkedSName = rs.getString("name");
				sources.add(rf);
			}
		} finally {
			if (pstmt != null) try { pstmt.close(); } catch (Exception e) {}
		}
		return sources;
	}

	/*
	 * Clear the linked_forms cache for every survey in the linker bundle so the CSV files
	 * are regenerated with the new filter on the next download.
	 */
	private void invalidateLinkerFiles(Connection sd, String linkerSIdent) throws Exception {
		ExternalFileManager efm = new ExternalFileManager(localisation);
		HashMap<Integer, Integer> groupSurveys = GeneralUtilityMethods.getGroupSurveys(sd, linkerSIdent);
		for (Integer sId : groupSurveys.keySet()) {
			efm.linkerChanged(sd, sId);
		}
	}
}
